read_from_file: false

matrices_file_path: $(find apf_pf)/configs/

n_threads: 1

distance_interval: 0.1

pixel_interval: 50

min_distance: 0.1 # cannot be zero to avoid repulsive potential nans

max_distance: 1.2

n_particles_vox: 20000

outliers_per_voxel: 10

trans_noise_sdev: [8, 0.4] # voxels, distance
obsv_noise_sdev: [170, 60] # confidence points, nOutliers

max_action_values: [0.0, 0.8, 0.8] 
min_action_values: [-0.8, -0.8, -0.8]
action_intervals: [0.2, 0.2, 0.2]

reward_Q: [0.7, 0.7, 0.7]
repulsive_potential_max_distance: 1.8 # corners of voxel grid maybe more than max_distance, check obstacle at the boundary after changing for reverse potential
repulsive_potential_gain: 2.0

alpha_vector_iterations: 20

lookahead_time: 0.5
sampling_time: 0.1
base_frame_id: base_link

output_apf: false
output_qmdp: true

publish_viz: true
display_cout: false
