att_vel: [0.6, 0.6, 1.3]
rep_vec_timeout_secs: 1.0
process_rate_secs: 0.067
success_radius: 0.35
holonomic: false
yaw_err_bound_nonzero_fore_vel_in_rad: 1.57

mode: qmdp
parabolic_attractor_bound: 0.5 # used only in apf mode
attractor_gain: 0.4 # used only in apf mode

display_cout: false

pose_frame_id: world

base_frame_id: base_link
pose_frame_output: true
